Added 3rd survey state of finished
based-4806/BasedSurvey pull request #109
Opened 2023-04-01 14:58 UTC by DavidSciola

Changed survey states from
open -> closed
to
being edited -> being filled -> finished

2023-04-01 15:03 UTC, DavidSciola commented
@DavidHaighton Note that I needed to change the application properties in main/src so that the app wouldn't use the actual Postgres db. I needed to do this because I changed the open/close bool of survey to an enum and the Postgres db is still using the open/close bool. At some point you will need to update the Postgres db.

2023-04-02 15:26 UTC, Shashaank5 approved these changes
Looks good overall. What was the purpose of adding the new columns finish and status instead of availability

2023-04-02 19:42 UTC, DavidHaighton requested changes
small  changes

2023-04-02 19:46 UTC, DavidHaighton commented on src/main/java/com/based/basedsurvey/controller/FillSurveyController.java
> +        // if survey is still being edited
need updated uml and readme

2023-04-02 19:46 UTC, DavidHaighton commented on src/test/resources/application.properties
> +#spring.datasource.username=sa
ill fix the postgress stuff first and then approve later

2023-04-05 03:31 UTC, DavidSciola commented
> Looks good overall. What was the purpose of adding the new columns finish and status instead of availability

I basically just renamed the availability column to status and the new finish column contains the button to finish a survey.

2023-04-05 03:47 UTC, DavidSciola commented on src/main/java/com/based/basedsurvey/controller/FillSurveyController.java
> +        // if survey is still being edited
done

2023-04-05 13:21 UTC, DavidHaighton commented
i cleared the entire production database lmao

2023-04-05 13:57 UTC, DavidHaighton approved these changes

2023-04-05 14:57 UTC, merged