Added based readme
based-4806/BasedSurvey pull request #25
Opened 2023-03-07 20:08 UTC by DavidHaighton

2023-03-07 20:15 UTC, kevinhquach approved these changes

2023-03-07 20:15 UTC, kevinhquach commented on README.md
> +There are unit tests for each of these functions.
based

2023-03-07 20:15 UTC, kevinhquach commented on README.md
> +View the documentation folder
images for schema and uml should be linked/embedded in the readme

2023-03-07 20:15 UTC, kevinhquach commented on README.md
> +⣿⡿⠋⠁⠀⠀⢀⣀⣠⡴⣸⣿⣇⡄⠀⠀⠀⠀⢀⡿⠄⠙⠛⠀⣀⣠⣤⣤⠄⠀
while very based, still need to explain what the project actually is

2023-03-07 20:21 UTC, kevinhquach requested changes

2023-03-07 20:25 UTC, DavidHaighton commented on README.md
> +⣿⡿⠋⠁⠀⠀⢀⣀⣠⡴⣸⣿⣇⡄⠀⠀⠀⠀⢀⡿⠄⠙⠛⠀⣀⣠⣤⣤⠄⠀
Frfr

2023-03-07 21:00 UTC, DavidHaighton commented on README.md
> +View the documentation folder
once the DB issue schema is up, ill add them

2023-03-08 17:53 UTC, kevinhquach approved these changes

2023-03-08 17:53 UTC, merged