Added feature so that questions cannot be edited if survey is open
based-4806/BasedSurvey pull request #81
Opened 2023-03-21 17:15 UTC by mack-wallace

2023-03-21 21:52 UTC, DavidHaighton requested changes
add a test to make sure that this works properly. It'll be just like the test in your other PR

2023-03-22 00:11 UTC, mack-wallace commented
> add a test to make sure that this works properly. It'll be just like the test in your other PR

tests added!

2023-03-22 12:04 UTC, Shashaank5 commented
> add a test to make sure that this works properly. It'll be just like the test in your other PR

@mack-wallace resolve this issue and you should be good to go

2023-03-22 13:31 UTC, merged

2023-03-22 13:33 UTC, DavidSciola commented on src/main/resources/templates/EditQuestion.html
>    </div>
Maybe add a button to return home so the user is not stuck on the page

You can use the same button from SurveyFillIssue.html